export const card = [
    { id: 1, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 2, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 3, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 4, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 5, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 6, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 7, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 8, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 9, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" },
    { id: 10, img: "/vila.png", name: "Mushrif Village", date: "/date.svg", term: "Срок сдачи проекта: 1-й квартал 2027", dom: "/dom.svg", domtitle: "Вилла", kvadrat: "/kvadrat.svg", kvadrattitle: "от 262 м2", group: "/group.svg", grouptitle: "Select Group", map: "/map.svg", maptitle: "Bluewaters" }
]